spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: user
      password: password

    standby:
      jdbc-url: jdbc:postgresql://localhost:5433/postgres
      username: user
      password: password
    driver-class-name: org.postgresql.Driver
