spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
          time_zone: UTC

  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: user
      password: password

    standby:
      jdbc-url: jdbc:postgresql://localhost:5433/postgres
      username: user
      password: password
    driver-class-name: org.postgresql.Driver
